default_language_version:
  python: python3
repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        language: python
        args: [--py36-plus]
  - repo: https://github.com/ambv/black
    rev: 23.1.0
    hooks:
      - id: black
        language: python
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        # I want to keep very long lines csv example variables.
        # NOTE: this exlude is also set in pre-commit-config.yaml as pre-commit seems to ignore this here

        exclude: |
            (?x)^(
                tests/resources/test_mapper/example_mapping_inputs.py|
                tests/resources/test_mapper/example_sniffer_inputs.py|
                tests/mock_responses.py
            )$ 

        language: python
        additional_dependencies:
          - flake8-bugbear
          - pep8-naming
          - flake8-docstrings
          - mccabe
          - yesqa