language: python
python:
- 3.6
before_install:
- pip install codecov pytest-cov pyyaml factory_boy click pydicom fileselection tqdm
install:
- pip install -U tox-travis
script:
- tox
after_success:
- pytest --cov=./anonapi
- codecov
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: sjoerdk
  password:
    secure: B8X06NLrVOwS508NZW/vpN7WIYm6+jBt6WZTomXyKFh+9IbubEzbCaFqkROkTey4BGMzY7aNzd657p9F/zpv+3y+U3QdTOi9qq5eUOaYopKu8xnbaGefNmoHRY5lShM/JdyIZu4G+2MHzr5o/vhJxjiERs0Bg9UxzsobTCHwXRrj0nDgp0N6J0t15f76PBelNuxB6WDHfg+kQd2dTq+6/B3R7lYWS0VyWbmvtnCK3e4Tb4431y6LwQMwPmlPW9Eae+fgWgOT6hMxdAVYAF8b6lyl+UK554foc8SsO57wHpmebBhdvSotRjpQ8Ldy+wqtK0cEETbrMJufdfir2YbUzsOHcAKGWJ9mNEKP/ZX4XSTJY5qBY+OQ0FouilI64Kk6g+ONNvl8y7Y166SEeAGDRL5mG0XYOPaP73d41oVnnBu/azXdB20AM2AfVn8Sp3ZXCxP1gm0dG37C24Zh+xw5+S58kqchdAFeOxxQmQ3Q1pBK/MIghj9FUXB/Q2HntfOGA3CURrXBvCUOmRn7m51JCVJ6ltS6Fx1wocgpShTAT9g1A0pm7nNcpF3I7ZxXot3lHnRXtHeTguCkPUVOvgjazeNzj9xZZ0VPBgrJFlYJra778rh1Ywru8/YT6WuBXsuID6eBdnqkzQkZy6vz3m5mhPqAELL2iWe0SNIF1RkF9pg=
  on:
    tags: true
    repo: sjoerdk/anonapi
    python: 3.6
notifications:
  slack:
    secure: liDThGTqsJX/Tu0oESb+aL0bbP4+CyiuD0XxnZRCEzK9e5RxcDYdcNTnQj6k1cFVka8dYf5FIEsrYpH9aAiuIaNXkEHH510PTQilBdNo3GfkOBU0M3OhgXnP0QrZyTDhrOzO0KISrHyU0zoIm5YYng9LmOaZ06XZkh6bikX3v6BL89Vckuqf7tf9N7o/JFOCO74/4yreSgSo4J7Top/3Bp3usXNOESPa11+ky5rR4ROPu0cNeVg4eli37tLEOIeRE3BMvO0bgI3cfBr+XeTGHoN/G6nSm5Rc5pQr815G93IVRFo24bUtQLbumqVVqcA40Ez+N+fqZ3hi4fj5CEu5LJXLWA7dcH/2i3wNFOflCWvNrNC843zPVMt12fM1V1IAAhcKNKl7f4Yh7PLUeRptkgkxILpWT2izxEHaaw275PolRYQko6xw0Pwfv3FDZcxuZ6Y3B7E/7qyqNz+BISloHTToVXxoW3n4JaewoLkA5NMc0pSBv8DK9tF5HOxipK4k+LHhCAY5yFQV0Op6603EZTvCTPC2wFGChHNfGTPVAjWMDfPtcDPFtexjTwLYUphNPP/zEt+zcYNAyyug9LTIsGafw+yuMlBmo/L+2ZDwS1acAGX1qm9JPfWxW98cHgfPFtCkKKDwPX94fIW3X71qagXUbP81gxw/6d9+H4KBAEM=
