language: python
python:
- 3.6
install: pip install -U tox-travis
script:
    - tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: sjoerdk
  password:
    secure: B8X06NLrVOwS508NZW/vpN7WIYm6+jBt6WZTomXyKFh+9IbubEzbCaFqkROkTey4BGMzY7aNzd657p9F/zpv+3y+U3QdTOi9qq5eUOaYopKu8xnbaGefNmoHRY5lShM/JdyIZu4G+2MHzr5o/vhJxjiERs0Bg9UxzsobTCHwXRrj0nDgp0N6J0t15f76PBelNuxB6WDHfg+kQd2dTq+6/B3R7lYWS0VyWbmvtnCK3e4Tb4431y6LwQMwPmlPW9Eae+fgWgOT6hMxdAVYAF8b6lyl+UK554foc8SsO57wHpmebBhdvSotRjpQ8Ldy+wqtK0cEETbrMJufdfir2YbUzsOHcAKGWJ9mNEKP/ZX4XSTJY5qBY+OQ0FouilI64Kk6g+ONNvl8y7Y166SEeAGDRL5mG0XYOPaP73d41oVnnBu/azXdB20AM2AfVn8Sp3ZXCxP1gm0dG37C24Zh+xw5+S58kqchdAFeOxxQmQ3Q1pBK/MIghj9FUXB/Q2HntfOGA3CURrXBvCUOmRn7m51JCVJ6ltS6Fx1wocgpShTAT9g1A0pm7nNcpF3I7ZxXot3lHnRXtHeTguCkPUVOvgjazeNzj9xZZ0VPBgrJFlYJra778rh1Ywru8/YT6WuBXsuID6eBdnqkzQkZy6vz3m5mhPqAELL2iWe0SNIF1RkF9pg=
  on:
    tags: true
    repo: sjoerdk/anonapi
    python: 3.6
